name: Bug Report
description: Сообщить о баге
title: "[BUG] "
labels: ["type: bug", "status: ready"]
body:
  - type: textarea
    id: description
    attributes:
      label: Что произошло
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: issue_ref
    attributes:
      label: Связанный Issue (если есть)
      placeholder: "#12"
    validations:
      required: false
